import type { EtapeVisite } from './VisiteGuidee';

// ─── Les étapes de la visite guidée de Xena Horizon ─────────────────
// Une étape par section du back-office, dans l'ordre du menu, plus ce
// qui se passe sur le site public. Rien n'est inventé : chaque phrase
// reprend ce que la section fait vraiment.

export const ETAPES_VISITE: Record<'FR' | 'EN', EtapeVisite[]> = {
  FR: [
    { titre: 'Bonjour Laurie', corps: 'Cette visite fait le tour de votre site en quelques minutes, une section à la fois, et chaque carte ouvre la section dont elle parle pour que vous la voyiez avec vos vraies données. Vous pourrez la rouvrir quand vous voudrez par le bouton « Visite guidée » au bas du menu.' },
    { titre: 'Le tableau de bord', ancre: 'ADMIN_DASHBOARD', corps: 'C’est la page où vous arrivez chaque matin : les ventes du mois, les factures à recevoir, les demandes en attente et les clients actifs se lisent d’un coup d’œil, avec les dernières commandes en dessous. Rien ne s’y saisit à la main, tout vient des autres sections.' },
    { titre: 'Les dossiers de vos clients', ancre: 'ADMIN_DOSSIERS', corps: 'Chaque client qui ouvre son espace sur votre site a ici sa fiche : les pièces qu’il a déposées, où il en est dans le parcours en cinq temps, et votre fil de messages avec lui. Vous jugez une pièce, vous faites avancer l’étape d’un clic, et vous pouvez sortir la fiche en texte prêt pour un assistant ou en PDF.' },
    { titre: 'Le carnet de clients', ancre: 'ADMIN_CRM', corps: 'Le carnet garde une fiche par client ou par prospect, avec son statut et les tâches à faire pour lui, si bien que votre réseau tient à un seul endroit plutôt que dans trois feuilles de calcul. L’import et l’export vous laissent partir de votre liste actuelle.' },
    { titre: 'Vos offres', ancre: 'ADMIN_PRODUCTS', corps: 'Vos services et vos forfaits vivent ici comme un catalogue, rangés du moins cher au plus cher dans une échelle de valeur que vos clients lisent d’un regard. Quand le paiement en ligne est branché, chaque offre publiée crée d’elle-même son produit et son prix dans Stripe.' },
    { titre: 'Les factures', ancre: 'ADMIN_INVOICES', corps: 'Vous composez une facture à votre nom, vous l’envoyez, et votre client la paie par carte sur une page publique qui se consulte sans compte et s’imprime proprement. Le tableau de bord compte ensuite ce qui reste à encaisser.' },
    { titre: 'Les finances', ancre: 'ADMIN_FINANCE', corps: 'Une comptabilité complète vit dans votre site : le plan de comptes, les transactions, la conciliation avec vos relevés bancaires importés, les rapports, le calcul des taxes à remettre et une prévision d’impôt. Vous n’avez plus besoin d’un logiciel à côté pour tenir vos livres.' },
    { titre: 'L’agenda', ancre: 'ADMIN_AGENDA', corps: 'Vous posez vos disponibilités ici, et vos clients prennent rendez-vous directement sur le site, reçoivent leur confirmation avec un fichier pour leur propre agenda, puis se présentent à la rencontre vidéo intégrée sans quitter la page. Une fois branchée, la synchronisation avec votre agenda Google bloque aussi les heures où vous êtes déjà prise ailleurs.' },
    { titre: 'Le courriel et les messages', ancre: 'ADMIN_EMAIL', corps: 'Les demandes reçues par le site et les conversations avec vos clients se lisent au même endroit, chaque dossier montrant la personne et le fil complet. C’est la boîte que vous ouvrez après le tableau de bord.' },
    { titre: 'L’infolettre', ancre: 'ADMIN_NEWSLETTER', corps: 'Vous composez votre infolettre par blocs, vous choisissez à qui elle part, vous voyez le rendu exact du courriel avant l’envoi, et vous gérez votre liste d’abonnés sans passer par un service extérieur. L’envoi et le suivi des ouvertures s’activent dès que la clé de l’expéditeur est posée.' },
    { titre: 'La galerie', ancre: 'ADMIN_GALLERY', corps: 'Les photos et les vidéos qui paraissent sur votre site s’ajoutent, se retirent et se réordonnent ici, sans jamais toucher au code. Onze photos du site portent aussi un point de recadrage que vous déplacez vous-même dans le crayon d’édition.' },
    { titre: 'Le studio social', ancre: 'ADMIN_SOCIAL', corps: 'Un atelier graphique pour composer vos visuels Instagram et ceux des autres réseaux à partir de gabarits à vos couleurs. Vous déplacez les calques de texte, d’image et de forme, puis vous exportez en un clic.' },
    { titre: 'Les témoignages audio', ancre: 'ADMIN_TEMOIGNAGES', corps: 'Certains de vos clients se sont enregistrés pour parler de vous, et ces voix jouent directement dans la section « Ils en parlent » de l’accueil, entre les témoignages écrits. Vous les gérez ici.' },
    { titre: 'Les capsules', ancre: 'ADMIN_VIDEOS', corps: 'Vos capsules vidéo se rangent ici avant de paraître sur le site, et les épisodes de votre balado, eux, se mettent à jour d’eux-mêmes à chaque publication de votre flux.' },
    { titre: 'Les sections du site', ancre: 'ADMIN_SECTIONS', corps: 'Les grands blocs de votre page d’accueil se réorganisent ici, du portrait jusqu’aux projets, et chacun s’allume ou s’éteint d’un geste. Sur le site lui-même, le crayon en haut de page vous laisse changer presque tous les textes dans les deux langues, et le texte d’origine reste en réserve si vous voulez revenir en arrière.' },
    { titre: 'Le journal des changements', ancre: 'ADMIN_CHANGELOG', corps: 'Chaque mise à jour de votre site s’y explique en langage simple, sans jargon, pour que vous sachiez toujours ce que vous avez reçu et quand.' },
    { titre: 'Pour Vexel', ancre: 'ADMIN_VEXEL', corps: 'Un coffre chiffré dans votre navigateur avant l’envoi, où vous déposez les accès dont le studio a besoin pour ouvrir en votre nom les abonnements du site. Seul Alex peut le déchiffrer. C’est aussi ici que vous décrivez un changement que vous voulez sur votre site.' },
    { titre: 'Vous connaissez maintenant votre site', corps: 'Le site public se lit en français et en anglais, dans deux habillages de couleur et un mode nuit que le visiteur choisit, et chaque client qui ouvre son espace y trouve son dossier, ses rendez-vous et sa messagerie avec vous. Quand une question reste, écrivez au studio depuis la section « Pour Vexel » : elle arrive directement à Alex.' },
  ],
  EN: [
    { titre: 'Hello Laurie', corps: 'This tour walks through your site in a few minutes, one section at a time, and every card opens the section it describes so you see it with your real data. You can reopen it any time with the “Guided tour” button at the bottom of the menu.' },
    { titre: 'The dashboard', ancre: 'ADMIN_DASHBOARD', corps: 'This is where you land every morning: sales for the month, invoices outstanding, pending requests and active clients read at a glance, with the latest orders below. Nothing is typed here, everything comes from the other sections.' },
    { titre: 'Your client files', ancre: 'ADMIN_DOSSIERS', corps: 'Every client who opens their space on your site has a file here: the pieces they uploaded, where they stand on the five-step path, and your message thread with them. You judge a piece, move the step forward with one click, and export the file as assistant-ready text or as a PDF.' },
    { titre: 'The client book', ancre: 'ADMIN_CRM', corps: 'One card per client or prospect, with a status and the tasks to do for them, so your network lives in one place rather than in three spreadsheets. Import and export let you start from your current list.' },
    { titre: 'Your offers', ancre: 'ADMIN_PRODUCTS', corps: 'Your services and packages live here as a catalogue, ranked from the least to the most expensive on a value ladder your clients read at a glance. Once online payment is connected, each published offer creates its own product and price in Stripe.' },
    { titre: 'Invoices', ancre: 'ADMIN_INVOICES', corps: 'You compose an invoice in your name, send it, and your client pays by card on a public page that needs no account and prints cleanly. The dashboard then counts what is still to collect.' },
    { titre: 'Finances', ancre: 'ADMIN_FINANCE', corps: 'A full set of books lives in your site: chart of accounts, transactions, reconciliation with imported bank statements, reports, the taxes to remit and a tax forecast. You no longer need a separate accounting tool.' },
    { titre: 'The calendar', ancre: 'ADMIN_AGENDA', corps: 'You set your availability here, and clients book directly on the site, receive their confirmation with a file for their own calendar, then join the built-in video meeting without leaving the page. Once connected, the Google Calendar sync also blocks the hours you are already busy elsewhere.' },
    { titre: 'Email and messages', ancre: 'ADMIN_EMAIL', corps: 'Requests received through the site and conversations with your clients read in one place, each file showing the person and the full thread. It is the inbox you open right after the dashboard.' },
    { titre: 'The newsletter', ancre: 'ADMIN_NEWSLETTER', corps: 'You compose your newsletter in blocks, choose who receives it, preview the exact email before sending, and manage your subscriber list without an outside service. Sending and open tracking switch on as soon as the sender key is set.' },
    { titre: 'The gallery', ancre: 'ADMIN_GALLERY', corps: 'The photos and videos shown on your site are added, removed and reordered here, never through code. Eleven site photos also carry a focal point you move yourself in the editing pencil.' },
    { titre: 'The social studio', ancre: 'ADMIN_SOCIAL', corps: 'A graphic workshop to compose your Instagram and other social visuals from templates in your colours. You move text, image and shape layers, then export in one click.' },
    { titre: 'Audio testimonials', ancre: 'ADMIN_TEMOIGNAGES', corps: 'Some of your clients recorded themselves talking about you, and those voices play right inside the “They talk about it” section of the home page, among the written testimonials. You manage them here.' },
    { titre: 'Capsules', ancre: 'ADMIN_VIDEOS', corps: 'Your video capsules are filed here before appearing on the site, while your podcast episodes update on their own every time your feed publishes.' },
    { titre: 'Site sections', ancre: 'ADMIN_SECTIONS', corps: 'The big blocks of your home page, the portrait, the projects and the others, are reordered and switched on or off from here. On the site itself, the pencil at the top lets you change almost every text in both languages, with the original kept in reserve if you want to go back.' },
    { titre: 'The change log', ancre: 'ADMIN_CHANGELOG', corps: 'Every update to your site is explained here in plain words, no jargon, so you always know what you received and when.' },
    { titre: 'For Vexel', ancre: 'ADMIN_VEXEL', corps: 'A vault encrypted in your browser before sending, where you leave the access the studio needs to open the site’s subscriptions in your name. Only Alex can decrypt it. It is also where you describe a change you want on your site.' },
    { titre: 'You now know your site', corps: 'The public site reads in French and in English, in two colour palettes and a night mode the visitor chooses, and every client who opens their space finds their file, their appointments and their messages with you. When a question remains, write to the studio from the “For Vexel” section: it reaches Alex directly.' },
  ],
};

export const LIBELLES_VISITE = {
  FR: { visite: 'Visite guidée', etape: 'Étape', precedent: 'Précédent', suivant: 'Suivant', terminer: 'Terminer', quitter: 'Quitter' },
  EN: { visite: 'Guided tour', etape: 'Step', precedent: 'Back', suivant: 'Next', terminer: 'Done', quitter: 'Quit' },
};
